# https://www.home-assistant.io/integrations/default_config/
# default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
      allow_bypass_login: true

# discovery: ~
# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.integration_linear: debug
